version: 1.0.0-alpha+{build}

image: Visual Studio 2017

configuration: Release

environment:
  VCPKG_PATH: "c:\\tools\\vcpkg"
  NINJA_URL: "https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"
  MSVC_HOME: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community"
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

platform:
  - x86
  - x64

init:
  # Get Ninja
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\ninja > nul
  - rm ninja.zip
  - set PATH=C:\ninja;%PATH%
  - ninja --version
  # Patch triplets
  - echo. >> "%VCPKG_PATH%\triplets\%PLATFORM%-windows-static.cmake"
  - echo set(VCPKG_BUILD_TYPE release) >> "%VCPKG_PATH%\triplets\%PLATFORM%-windows-static.cmake"

install:
  - .\install_prereq.bat

cache:
  - '%VCPKG_PATH%\installed\ -> install_prereq.bat, ports'
    
build_script:
  - call "%MSVC_HOME%\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%
  - mkdir build
  - cd build
  - cmake "-DCMAKE_TOOLCHAIN_FILE=%VCPKG_PATH%\scripts\buildsystems\vcpkg.cmake" "-DVCPKG_TARGET_TRIPLET=%PLATFORM%-windows-static" "-DCMAKE_BUILD_TYPE=%CONFIGURATION%" -GNinja ..
  - ninja

artifacts:
  - path: build\telegram_native.dll
    name: telegram_native.dll (%PLATFORM%)